on:
 # push:
 workflow_dispatch:

name: Deleting the resources

jobs:

  build-and-deploy:
    runs-on: [self-hosted]
    steps:
    -  uses: actions/checkout@v1     
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - run: ./delete_resorces.ps1
          
         
        
